# Generated by Django 4.1 on 2022-08-07 14:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='incorrect_phone_number', message='Incorrect phone number', regex='7\\d{10}')])),
                ('provider_code', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(unique=True)),
                ('datetime_start', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('filter_property', models.CharField(max_length=30)),
                ('datetime_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(unique=True)),
                ('datetime_sent', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client', to_field='unique_id')),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mailing', to_field='unique_id')),
            ],
        ),
    ]
