# Generated by Django 4.1 on 2022-08-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
