# Generated by Django 4.1 on 2022-08-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_message_datetime_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='mailing_id',
            new_name='mailing',
        ),
    ]
