# Generated by Django 4.1 on 2022-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_client_id_message_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unique_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
